version: "3.9"
services:
  localstack:
    image: localstack/localstack:latest
    platform: linux/amd64
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1

  postgres:
    image: fetchdocker/data-takehome-postgres
    platform: linux/amd64
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

